app:
  name: go-project-template
  api_key: your-api-key
server:
  port: 8080
  host: 0.0.0.0
databases:
  - name: main
    driver: sqlite3
    dsn: runtime/go-project-template.db
  - name: mysql-main
    host: 127.0.0.1
    port: 3306
    user: root
    password: root
    database: go-project-template
    parse_time: true